export const GET_ADVENTURES = 'GET_ADVENTURES';
export const ADD_ADVENTURE = 'ADD_ADVENTURE';
export const DELETE_ADVENTURE = 'DELETE_ADVENTURE';
export const UPDATE_ADVENTURE = 'UPDATE_ADVENTURE';

export const SET_ADVENTURE_FOR_EDIT = 'SET_ADVENTURE_FOR_EDIT'
export const CLEAR_ADVENTURE_FOR_EDIT = 'CLEAR_ADVENTURE_FOR_EDIT'

export const SPINNER_ON = 'SPINNER_ON';
export const SPINNER_OFF = 'SPINNER_OFF';

export const THROW_ERROR = 'THROW_ERROR';

export const SET_LOGGED_IN_USER = 'SET_LOGGED_IN_USER'
export const CLEAR_LOGGED_IN_USER = 'CLEAR_LOGGED_IN_USER'